stages:
    - build
    - test
    - deploy
    
maven-build:
    stage: build
    tags:
        - backend_spring_runner
    script:
        - cd Backend/webAPI
        - mvn package -B
        
maven-test:
    stage: test
    tags:
        - backend_spring_runner
    script:
        - cd Backend/webAPI
        - mvn test

api-docs-build:
    stage: build
    tags:
        - backend_spring_runner
    script:
        - cd Backend/apiDocs
        - scl enable rh-ruby23 bash
        - gem install bundler
        - bundle install
        - bundle exec middleman build
        
api-docs-deploy:
    stage: deploy
    tags:
        - backend_spring_runner
    script:
        - cd Backend/apiDocs
        - cp -r build/* ../../../var/www/apiDocs/
        
web-api-deploy:
    stage: deploy
    tags:
        - backend_spring_runner
    script:
        - cd Backend/webAPI
        - mvn package
        - sudo mv target/*.jar /home/webAPI/web-api.jar
        - sudo systemctl stop system-web-api
        - sudo systemctl start system-web-api
    when: manual
    only:
        - master