stages:
    - mavenbuild
    - apidocsbuild
    - reactbuild
    - autoDeploy
    
maven-build:
    stage: mavenbuild
    tags:
        - backend_spring_runner
    script:
        - cd Backend/webAPI
        - mvn package -B
        
apidocsbuild:
    stage: apidocsbuild
    tags:
        - backend_spring_runner
    script:
        - cd Backend/apiDocs
        - scl enable rh-ruby23 bash
        - bundler exec middleman build
        - cp -r build/* ../../../var/www/apiDocs/
        
autoDeploySpring:
    stage: autoDeploy
    tags:
        - backend_spring_runner
    script:
        - cd Backend/webAPI
        - mvn package
        - sudo mv target/*.jar /home/webAPI/web-api.jar
        - sudo systemctl stop system-web-api
        - sudo systemctl start system-web-api